EaglesNestMMA/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace EaglesNestMMA.Models
{
    public class Contact
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [MaxLength(255)]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public int PhoneNumber { get; set; }

        [Required]
        public string Message { get; set; }
    }
}

EaglesNestMMA/Controllers/EmailController.cs
using EaglesNestMMA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace EaglesNestMMA.Controllers
{
    public class EmailController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Email
        public ActionResult Index()
        {
            return View();
        }

        // Called when user clicks the submit button and form values are passed into it
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SendContactUsEmail(Contact contact)
        {
        
            if (ModelState.IsValid)
            {
                db.Contacts.Add(contact);
                db.SaveChanges();

                var name = contact.Name;
                var email = contact.Email;
                var phone = contact.PhoneNumber;
                var messages = contact.Message;
                var x = await EmailStatus(name, email, messages, phone);
                if (x == "sent")
                    ViewData["esent"] = "Your Message Has Been Sent";
                return RedirectToAction("Index", "Home");
            }

            var model = new Contact
            {
                Name = contact.Name,
                PhoneNumber = contact.PhoneNumber,
                Email = contact.Email,
                Message = contact.Message
            };
            return View("Contact", model);

        }


        private async Task<string> EmailStatus(string name, string email, string messages, int phone)
        {
            var message = new MailMessage();
            message.To.Add(new MailAddress("etest1482@gmail.com"));    
            message.From = new MailAddress("etest1482@gmail.com");   
            message.Subject = "Message From" + email;
            message.Body = "Name: " + name + "\nFrom: " + email + "\nPhone: " + phone + "\nMessage: " + messages;
            message.IsBodyHtml = true;
            using (var smtp = new SmtpClient())
            {
                var credential = new NetworkCredential
                {
                    UserName = "etest1482@gmail.com",  
                    Password = "Password1482%"   
                };

                // email server settings
                smtp.Credentials = credential;
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.EnableSsl = true;
                await smtp.SendMailAsync(message);

                return "sent";
            }
        }
    }
}

EaglesNestMMA/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EaglesNestMMA.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult About()
        {

            return View();
        }


        public ActionResult Contact()
        {

            return View();
        }


        public ActionResult Classes()
        {
            return View();
        }


        public ActionResult Schedule()
        {
            return View();
        }


        public ActionResult Testimonials()
        {
            return View();
        }


        public ActionResult Sponsors()
        {
            return View();
        }


        public ActionResult Register()
        {
            return View();
        }


        public ActionResult Login()
        {
            return View();
        }


    }
}

EaglesNestMMA/Views/Home/About.cshtml
@{
    ViewBag.Title = "Eagle's Nest | About";
}

<div class="banner">
    <h3 class="banner-text">About Us</h3>
</div>

<div class="contents about-contents">
    <div class="intro about-intro">
        <hr class="hr-dashed-red-med" />
        <p class="section-text about-text">
            Eagle's Nest MMA has been in existence for over 10 years founded and owned by Anselmo <br /> Martinez. Our
            aim is to touch the lives of individuals and families by helping them become <br />healthier from the inside
            out through martial arts and fitness. We have classes for men, women, <br /> athelets, and non-athelets, competitors,
            and children. We have youth and adult competition teams<br /> competing in kickboxing, MMA, jiu-jitsu, boxing, and
            karate. We are passionate about martial <br /> arts and we are passionate about helping people on their journey
            to fitness in a safe, fun, <br /> encouraging environment.
        </p>
        <hr class="hr-dashed-red-med" />
    </div>
    <div class="anselmo-div">
        <p class="section-header-text">ANSELMO MARTINEZ</p>
        <hr class="hr-dashed-red anselmo-underline" />
        <p class="section-text">
            Anselmo Martinez, the founder and owner of Eagle's Nest MMA, is a veteran <br />
            fighter of many styles having successfully competed as an amateur in <br />
            kickboxing, boxing, jiu-jitsu, and mma. He pursued his success into <br />
            professional competitions that included mma, boxing, and kickboxing. <br />
            Anselmo is currently a jiu-jitsu brown belt under Professor Tony Bonello and <br />
            nearing his black belt promotion.  In addition to his fight career, Anselmo has <br />
            won World Championships in Ireland and Brazil.  His passion goes beyond the <br />
            competition as he has been an assistant coach on all three of the U.S. <br />
            National teams that competed, the most recent being the 2017 USA Team <br />
            competing at the 14th World Wushu Championships in Kazan Russia. <br />
        </p>
        <img src="~/Content/Images/anselmo.jpg" class="about-coach-img anselmo-img"/>
        <hr class="hr-dashed-red-long anselmo-underline-bottom" />
    </div>
    <div class="shannon-div">
        <p class="section-header-text shannon-name">SHANNON MORTON</p>
        <hr class="hr-dashed-red shannon-underline" />
        <p class="section-text shannon-summary">
            Shannon Morton is co-owner of Eagle’s Nest and founder of ENMMA <br />
            Nutrition Coaching. She is a certified personal trainer through ISSA. She<br />
            also holds a third degree black belt in Shotokan karate and is a professional<br />
            kickboxer.  She has been a member of kickboxing Team USA, traveling and<br />
            competing internationally with KICK International and WAKO.  She most<br />
            recently competed in the Sanda portion of the 2017 14th World Wushu<br />
            Championships as part of the USA Team.
        </p>
        <img src="~/Content/Images/shannon.jpg" class="about-coach-img shannon-img"/>
        <hr class="hr-dashed-red-long shannon-underline-bottom" />
    </div>
</div>

EaglesNestMMA/Views/Home/Classes.cshtml
@{
    ViewBag.Title = "Eagle's Nest | Classes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="banner">
    <h3 class="banner-text">Classes</h3>
</div>

<div class="contents classes-contents">
    <ul class="martial-arts-list classes-list-right">
        <li><p class="section-header-text">MARTIAL ARTS</p></li>
        <li><hr class="hr-dashed-red" /></li>
        <li><p class="section-text">Brazilian Jiu-Jitsu</p></li>
        <li>
            <p class="classes-text">Our Jiu-Jitsu classes are designed to teach any individual specific grappling techniques that will build their confidence,<br />
            increase their strength, and challenge their conditioning. We offer both Gi and no Gi Jiu-Jitsu. Our style of bjj is not just<br />
            a competition style, but one that is proven in MMA. We incorporate wrestling takedowns, Muay Thai clinch, and even<br />
            ground and pound to better enhance our bjj strategy.</p>
        </li>
        <li><hr class="hr-dashed-red-900" /></li>
        <li><p class="section-text">Kickboxing & Boxing</p></li>
        <li>
            <p class="classes-text">
                Our kickboxing classes are open to competitors and non-competitors alike.  Not only will you get a great workout, but<br />
                you will also develop real, valuable kickboxing and boxing skills as you get into optimal shape. You’ll improve your<br />
                abilities in punching, kicking and kneeing techniques as well as your footwork and body mechanics.  Our bag<br />
                workouts are designed to help you reach your fitness goals and improve your skills. Most importantly, the workouts<br />
                are challenging and fun!
            </p>
        </li>
        <li><hr class="hr-dashed-red-900" /></li>
        <li><p class="section-text">Mixed Martial Arts</p></li>
        <li>
            <p class="classes-text">
                MMA is a fundamentals class that is so challenging and exciting. From beginner to advanced, everyone is pushed to<br />
                their limits. Primarily we work in circuits with a partner. Our circuits are designed to create real life scenarios and the<br />
                obstacles we will face, as well as those we could expect in a cage fight. Self- defense drills are combined in such a way<br />
                as to challenge the mind and body.
            </p>
        </li>
        <li><hr class="hr-dashed-red-900" /></li>
    </ul>

    <ul class="fitness-list classes-list-left">
        <li><p class="section-header-text">FITNESS</p></li>
        <li><hr class="hr-dashed-red" /></li>
        <li><p class="section-text">Bootcamp</p></li>
        <li>
            <p class="classes-text">
                S&C is a 45 minute class focused on building muscle and increasing strength. We emphasize proper weight lifting techniques<br />
                and use exercise prescription specifically to improve performance in athletic competition and to get in great shape.
            </p>
        </li>
        <li><hr class="hr-dashed-red-900" /></li>
        <li><p class="section-text">Strength & Conditioning</p></li>
        <li>
            <p class="classes-text">
                Boot camp is a 45-60 minute class designed to build strength and fitness through a variety of intense group intervals. We<br />
                focus on fat loss, an increase in cardiovascular efficiency, an increase in strength, and helping people get in the routine of<br />
                exercise in a fun, energetic environment.
            </p>
        </li>
        <li><hr class="hr-dashed-red-900" /></li>
        <li><p class="section-text">Yoga</p></li>
        <li>
            <p class="classes-text">
                Yoga is a 45 minute class designed to relax and rejuvenate! This class is great for beginners and seasoned athletes alike.
            </p>
        </li>
        <li><hr class="hr-dashed-red-900" /></li>
    </ul>


    <ul class="nutrition-list classes-list-right">
        <li><p class="section-header-text">NUTRITION</p></li>
        <li><hr class="hr-dashed-red" /></li>
        <li><p class="section-text">Nutrition Coaching</p></li>
        <li>
            <p class="classes-text">
                Eagle’s Nest MMA is committed to helping you reach your full potential in bettering your health and wellness both<br />
                inside and out! As we know so well, fitness is 20% exercise and 80% nutrition. We have an online nutrition coaching<br />
                system that will absolutely get you results! It works if YOU work! We are also a proud distributor of Juice Plus+ for both<br />
                adults and children for optimal nutrition!
            </p>
        </li>
        <li><hr class="hr-dashed-red-900" /></li>
    </ul>


    <ul class="kids-list classes-list-left">
        <li><p class="section-header-text">KIDS MARTIAL ARTS</p></li>
        <li><hr class="hr-dashed-red" /></li>
        <li><p class="section-text">MMA Kids, Jiu-Jitsu Kids, & Karate Kids</p></li>
        <li>
            <p class="classes-text">
                Empower your child with positive character traits such as self- confidence and a winning attitude that may impact their lives<br />
                in amazing ways and set into motion a series of successes that can last a lifetime! At Eagle’s Nest MMA we strive to instill<br />
                values such as respect, responsibility, integrity, and discipline in to our students. Our programs will bring out their<br />
                athleticism and set them on the path of fitness as a lifestyle! In a society where bullying is a threat, we also teach bully<br />
                prevention. Our students are taught how to avoid potentially threatening situation and how to just “walk away.” They are<br />
                also taught how to defend themselves should they be attacked.
            </p>
        </li>
        <li><hr class="hr-dashed-red-900" /></li>
    </ul>


    <ul class="dropin-list classes-list-right">
        <li><p class="section-header-text">ADULT DROP-IN TRAINING</p></li>
        <li><hr class="hr-dashed-red" /></li>
        <li><p class="section-text">Drop-ins welcome!</p></li>
        <li>
            <p class="classes-text">
                Attend any of our classes for $10 per day.
            </p>
        </li>
        <li><hr class="hr-dashed-red" /></li>
        <li><btn class="btn registration-btn" onclick="window.open('https://www.paypal.me/eaglesnestmma')">Registration and<br />Payment</btn></li>
    </ul>

</div>

EaglesNestMMA/Views/Home/Contact.cshtml
@model EaglesNestMMA.Models.Contact

@{
    ViewBag.Title = "Eagle's Nest | Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="banner">
    <h3 class="banner-text">Contact Us</h3>
</div>

<div class="contents contact-contents">
    <div class="contact-info-div">
        <ul class="contact-info-list">
            <li>
                <div class="black-circle">
                    <img class="contact-icon" />
                </div>
                <p class="contact-info-title phone-title">Telephone</p>
                <div class="contact-info-container">
                    <p class="contact-info-text phone">Phone: (806) 687-6671</p>
                </div>
            </li>
            <li>
                <div class="black-circle">
                    <img class="contact-icon" />
                </div>
                <p class="contact-info-title address-title">Address</p>
                <div class="contact-info-container">
                    <p class="contact-info-text address">5278 34th St. <br />Lubbock, TX 79424</p>
                </div>
            </li>
            <li>
                <div class="black-circle">
                    <img class="contact-icon" />
                </div>
                <p class="contact-info-title email-title">Email</p>
                <div class="contact-info-container">
                    <p class="contact-info-text email">eaglesnest<br />mma@gmail.com</p>
                </div>
            </li>
        </ul>
    </div>

    @using (Html.BeginForm("SendContactUsEmail", "Email", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="contact-form">
            <div class="form-group col-lg-10">
                @Html.LabelFor(model => model.Name)
                @Html.TextBoxFor(model => model.Name, new { name = "sname", type = "text", @class = "form-control contact-input contact-form-name" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
            <div class="form-group col-lg-10">
                @Html.LabelFor(model => model.Email)
                @Html.TextBoxFor(model => model.Email, new { name = "semail", type = "email", @class = "form-control contact-input contact-form-email" })
                @Html.ValidationMessageFor(model => model.Email)
            </div>
            <div class="form-group col-lg-10">
                @Html.LabelFor(model => model.PhoneNumber)
                @Html.TextBoxFor(model => model.PhoneNumber, new { name = "sphone", type = "tel", @class = "form-control contact-input contact-form-phone" })
                @Html.ValidationMessageFor(model => model.PhoneNumber)
            </div>
            <div class="form-group col-lg-10">
                @Html.LabelFor(model => model.Message)
                @Html.TextAreaFor(model => model.Message, new { name = "smessage", type = "text", @class = "form-control contact-input contact-form-message", rows = "5" })
                @Html.ValidationMessageFor(model => model.Message)
            </div>
            <div class="form-group col-lg-10">
                <button type="submit" onclick="this.form.submit()" class="btn btn-primary form-control contact-form-submit">Submit</button>
            </div>
        </div>
    }

    <iframe class="contact-map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3324.6059780703026!2d-101.92810488540289!3d33.56361235076976!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86fe72da81be7d61%3A0x69852de7c804758!2s5278+34th+St%2C+Lubbock%2C+TX+79407!5e0!3m2!1sen!2sus!4v1510243728371" width="300" height="392" frameborder="0" allowfullscreen></iframe>

    <div class="social-media-div">
        <ul class="social-media-list">
            <li class="social-media-icon"><a href="#" class="fa fa-facebook"></a></li>
            <li class="social-media-icon"><a href="#" class="fa fa-twitter"></a></li>
            <li class="social-media-icon"><a href="#" class="fa fa-instagram"></a></li>
            <li class="social-media-icon"><a href="#" class="fa fa-youtube"></a></li>
        </ul>
    </div>
</div>

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

EaglesNestMMA/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Eagle's Nest MMA";
}

<div class="hero">
    <img class="hands" src="~/Content/Images/hands2.png" />
    <p class="hero-text">On the streets you fight <br /> to live...in the cage you<br /> live to fight again.</p>
</div>

<div class="section-one">
    <ul class="section-one-ul">
        <li><p class="welcome-title">WELCOME TO EAGLE'S NEST</p></li>
        <li><div class="horizontal-dashed-red home-s2-line"></div> </li>
        <li>
            <p class="welcome-text">
                Eagle's Nest was born of necessity and shaped by determination. We were a group of kickboxers and grapplers <br />
                without direction, and have now evolved into a well rounded team that competes world wide in kickboxing, MMA, <br />
                jiu-jitsu, and karate. We have even gone further by implementing a strength and conditioning program as well as nutritional<br />
                coaching for the highest level of atheletic performance. Our aim is to encourage individuals and families to lead healthier <br />
                lifestyles, and to assis them in raching their martial arts and fitness related goals. We seek to touch the lives of as many <br />
                individuals as possible with the positive benefits of the martial arts.
            </p>
        </li>
    </ul>
</div>

<div class="section-two">
    <div class="martial-arts">
        <h2 class="section-header">MARTIAL ARTS</h2>
        <hr class="hr-dashed-red martial-arts-red-line" />
        <ul class="content-list">
            <li>
                <div class="red-circle">
                    <div class="circle-image">
                        <img class="inner-img" src="~/Content/Images/mmaFighter.jpg" />
                    </div>
                </div>
                <a href="http://localhost:50266/Home/Classes#MMAclass" class="service-text home-link MMA">MMA</a>
            </li>
            <li>
                <div class="red-circle">
                    <div class="circle-image">
                        <img class="inner-img" src="~/Content/Images/boxer.jpg" />
                    </div>
                </div>
                <a href="http://localhost:50266/Home/Classes#kbclass" class="service-text home-link kb">Kickboxing & Boxing</a>
            </li>
            <li>
                <div class="red-circle">
                    <div class="circle-image">
                        <img class="inner-img" src="~/Content/Images/bjj.jpg" />
                    </div>
                </div>
                <a href="http://localhost:50266/Home/Classes#jjclass" class="service-text home-link jj">Jiu-Jitsu</a>
            </li>
            <li>
                <div class="red-circle">
                    <div class="circle-image">
                        <img class="inner-img" src="~/Content/Images/girlKarate.jpg" />
                    </div>
                </div>
                <a href="http://localhost:50266/Home/Classes#kidsclass" class="service-text home-link kids">Kids Program</a>
            </li>
        </ul>
        <hr class="hr-dashed-red-long s2-hr2"/>
    </div>

    <div class="fitness-nutrition">
        <h2 class="section-header">FITNESS & NUTRITION</h2>
        <hr class="hr-dashed-red fn-red-line"/>
        <ul class="content-list fn-list">
            <li>
                <div class="red-circle">
                    <div class="circle-image">
                        <img class="inner-img" src="~/Content/Images/strength.jpg" />
                    </div>
                </div>
                <a href="http://localhost:50266/Home/Classes#fitnessclass" class="service-text home-link fitness">Fitness Classes</a>
            </li>
            <li>
                <div class="red-circle">
                    <div class="circle-image">
                        <img class="inner-img" src="~/Content/Images/healthy-eating-diet.jpg" />
                    </div>
                </div>
                <a href="http://localhost:50266/Home/Classes#nutritionclass" class="service-text home-link nutrition">Nutrition</a>
            </li>
        </ul>
        <hr class="hr-dashed-red-long fn-bottom-red-line"/>
    </div>

    <div class="apparel">
        <h2 class="section-header apparel-header">APPAREL</h2>
        <hr class="hr-dashed-red apparel-red-line"/>
        <ul class="content-list ap-list" >
            <li>
                <div class="red-circle">
                    <div class="circle-image">
                        <img class="inner-img" src="~/Content/Images/longSleeveTee.jpg" />
                    </div>
                </div>
                <a href="https://teespring.com/stores/eagles-nest-mma" class="service-text home-link gym-apparel-text">Gym Apparel</a>
            </li>
        </ul>
        <hr class="hr-dashed-red-long apparel-bottom-red-line"/>

    </div>
</div>

EaglesNestMMA/Views/Home/Schedule.cshtml
@{
    ViewBag.Title = "Eagle's Nest | Schedule";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="banner">
    <h3 class="banner-text">Schedule</h3>
</div>

<div class="contents schedule-contents">
    <div class="schedule-div">
        <p class="section-header-text">ADULT SCHEDULE</p>
        <hr class="hr-dashed-red-900" />
        <table class="schedule">
            <tr>
                <th>MONDAY</th>
                <th>TUESDAY</th>
                <th>WEDNESDAY</th>
                <th>THURSDAY</th>
                <th>FRIDAY</th>
                <th>SATURDAY</th>
            </tr>
            <tr>
                <td>
                    5:15AM<br />
                    STRENGTH<br />
                    ​TRAINING<br />
                </td>
                <td>
                    5:15AM<br />
                    KICKBOXING<br />
                </td>
                <td>
                    5:15AM<br />
                    STRENGTH<br />
                    ​TRAINING<br />
                </td>
                <td>
                    5:15AM<br />
                    YOGA - SIGN<br />
                    ​UP ONLY<br />
                </td>
                <td>
                    5:15AM<br />
                    STRENGTH/<br />
                    ​KICKBOXING<br />
                </td>
                <td>
                    8AM<br />
                    YOGA<br />
                </td>
            </tr>
            <tr>
                <td>
                    8:30AM<br />
                    STRENGTH &<br />
                    KICKBOXING<br />
                    WOMEN ONLY<br />
                </td>
                <td></td>
                <td>
                    8:30AM<br />
                    STRENGTH &<br />
                    KICKBOXING<br />
                    WOMEN ONLY<br />
                </td>
                <td></td>
                <td>
                    8:30AM<br />
                    STRENGTH &<br />
                    KICKBOXING<br />
                </td>
                <td>
                    9AM<br />
                    STRENGTH<br />
                    TRAINING<br />
                </td>
            </tr>
            <tr>
                <td>
                    12PM<br />
                    KICKBOXING<br />
                </td>
                <td></td>
                <td>
                    12PM<br />
                    STRENGTH &<br />
                    KICKBOXING<br />
                </td>
                <td></td>
                <td>
                    5PM<br />
                    KARATE<br />
                </td>
                <td>
                    10AM<br />
                    KICKBOXING<br />
                </td>
            </tr>
            <tr>
                <td>
                    5:15PM<br />
                    BOOTCAMP<br />
                </td>
                <td>
                    5:15PM<br />
                    STRENGTH<br />
                    TRAINING<br />
                </td>
                <td>
                    5:15PM<br />
                    ​BOOTCAMP<br />
                </td>
                <td>
                    5:15PM<br />
                    STRENGTH<br />
                    TRAINING<br />
                </td>
                <td></td>
                <td>
                    11AM<br />
                    JIU-JITSU (Gi)<br />
                </td>
            </tr>
            <tr>
                <td>
                    6:30PM<br />
                    KICKBOXING<br />
                </td>
                <td>
                    6PM<br />
                    MMA CARDIO<br />
                </td>
                <td>
                    6PM<br />
                    KICKBOXING<br />
                </td>
                <td>
                    6PM<br />
                    MMA CARDIO<br />
                </td>
                <td>
                    6PM<br />
                    KICKBOXING<br />
                </td>
                <td>
                    12PM<br />
                    OPEN MAT<br />
                </td>
            </tr>
            <tr>
                <td>
                    7:15PM<br />
                    BOXING<br />
                </td>
                <td>
                    7PM<br />
                    JIU-JITSU<br />
                </td>
                <td>
                    6:45PM<br />
                    JIU-JITSU (Gi)<br />
                </td>
                <td>
                    7PM<br />
                    JIU-JITSU<br />
                </td>
                <td>
                    7PM<br />
                    BOXING<br />
                </td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>
                    8PM<br />
                    SPARRING<br />
                </td>
                <td></td>
                <td>
                    8PM<br />
                    SPARRING<br />
                </td>
                <td></td>
                <td></td>
            </tr>
        </table>
        <hr class="hr-dashed-red-900" />
    </div>

    <div class="schedule-div youth-section">
        <p class="section-header-text">YOUTH SCHEDULE</p>
        <hr class="hr-dashed-red-900" />
        <table class="schedule">
            <tr>
                <th>MONDAY</th>
                <th>TUESDAY</th>
                <th>WEDNESDAY</th>
                <th>THURSDAY</th>
                <th>FRIDAY</th>
                <th>SATURDAY</th>
            </tr>
            <tr>
                <td>
                    4:30PM<br />
                    LITTLE NINJAS<br />
                </td>
                <td></td>
                <td>
                    4:30PM<br />
                    ​LITTLE NINJAS<br />
                </td>
                <td></td>
                <td>
                    4:30PM<br />
                    ​LITTLE NINJAS<br />
                </td>
                <td>
                    12PM<br />
                    OPEN MAT<br />
                </td>
            </tr>
            <tr>
                <td>
                    5:15PM<br />
                    KARATE<br />
                </td>
                <td>
                    5:15PM<br />
                    ​MMA<br />
                </td>
                <td>
                    5:15PM<br />
                    ​KARATE<br />
                </td>
                <td>
                    5:15PM<br />
                    ​MMA<br />
                </td>
                <td>
                    5:15PM<br />
                    ​SPARRING<br />
                </td>
                <td></td>
            </tr>
            <tr>
                <td>
                    6:30PM<br />
                    KICKBOXING<br />
                    ​(10 and up)<br />
                </td>
                <td>
                    6PM<br />
                    MMA CARDIO<br />
                    (10 and up)<br />
                </td>
                <td>
                    6PM<br />
                    BJJ (Gi)<br />
                </td>
                <td>
                    6PM<br />
                    MMA CARDIO<br />
                    ​(10 and up)<br />
                </td>
                <td>
                    6PM<br />
                    ​KICKBOXING<br />
                    ​(10 and up)<br />
                </td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td>
                    7PM<br />
                    BJJ (No Gi)<br />
                    (12 and up)<br />
                </td>
                <td>
                    6PM<br />
                    KICKBOXING<br />
                    ​(10 and up)<br />
                </td>
                <td>
                    7PM<br />
                    BJJ (No Gi)<br />
                    ​(12 and up)<br />
                </td>
                <td></td>
                <td></td>
            </tr>
        </table>
        <hr class="hr-dashed-red-900" />
    </div>
</div>